name: py_binom
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_1
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - ncurses=6.4=h6a678d5_0
  - numpy=2.1.3=py313hf4aebb8_0
  - numpy-base=2.1.3=py313h3fc9231_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py313h06a4308_0
  - python=3.13.1=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - scipy=1.14.1=py313hf4aebb8_0
  - setuptools=72.1.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py313h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
prefix: /media/dude/DATA/anaconda3/envs/py_binom
